name: Build React application CI

on: [push]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - run: npm install

  check-linter:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: check-linter

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-build-dependencies-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - run: | 
          npm run build
          cp ./dist/index.html ./dist/404.html
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish:
    needs: build
#    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/github-pages.yml



